import { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { WbSunny, NightsStay } from "@material-ui/icons";
import styles from "./Layout.module.css";

interface LayoutProps {
  children: React.ReactNode;
  title?: string;
}

const Layout = ({ children, title = "Country List" }: LayoutProps) => {
  const [theme, setTheme] = useState("light");

  useEffect(() => {
    document.documentElement.setAttribute(
      "data-theme",
      localStorage.getItem("theme") || "{}"
    );

    setTheme(localStorage.getItem("theme") || "{}");
  }, []);

  const switchTheme = () => {
    if (theme === "light") {
      saveTheme("dark");
    } else {
      saveTheme("light");
    }
  };

  const saveTheme = (theme: string) => {
    setTheme(theme);
    localStorage.setItem("theme", theme);
    document.documentElement.setAttribute("data-theme", theme);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <div></div>
        <Link href="/">Country List</Link>

        <div style={{ float: "right" }}>
          <button className={styles.themeSwitcher} onClick={switchTheme}>
            {theme === "dark" ? <WbSunny /> : <NightsStay />}
          </button>
        </div>
      </header>
      <main className={styles.main}>{children}</main>

      <footer className={styles.footer}>jade bautista</footer>
    </div>
  );
};

export default Layout;
